name: environment
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - jupyterlab
  - ipykernel
  - numpy=1.26.*
  - pandas=2.3.*
  - scipy=1.15.*
  - matplotlib=3.10.*
  - bottleneck
  - numexpr
  - pillow
  - openpyxl
  - pip